matrix:
  include:
    - language: go
      go: 1.13.1
      env:
        - GO111MODULE=auto
      before_script:
        - cd golang
        - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.20.0
        - make install
      script:
        - make lint
        - go test ./x/relay/keeper
        - go test ./x/relay/types
        - go test -mod=readonly  `go list ./cli_test/...`

    - language: node_js
      node_js: 10.14.2
      before_script:
        - cd solidity
        - npm install -g truffle
        - npm install
      script:
        - npm run lint
        - npm run test
